### ISSUE TITLE
Selecting && operator

### ISSUE THREAD

**Issue by forReason** [paulyoder/LinqToExcel#120] opened 2017-08-07 18:34 UTC
Hello, when I use the && operator for a query i receive totally unpredictable and confusing results:

```var excel = new ExcelQueryFactory("products.xlsx");```

```c#
//discounts.count() = 51
var discounts = from s in excel.Worksheet() where
    s["Discount/Premium"].Cast<string>().StartsWith("-") select s;
MessageBox.Show(discounts.Count().ToString()); //<- returns 51
```

```c#
//discounts.count() = 8, should be 51
var discounts = from s in excel.Worksheet() where
    s["Discount/Premium"].Cast<string>().StartsWith("-")  &&
    s["YTM"].Cast<double>() > 3.0
    select s;
MessageBox.Show(discounts.Count().ToString()); //<- returns 8
```

```c#
applicable.count() = 51, as it should be
var discounts = from s in excel.Worksheet() where
    s["Discount/Premium"].Cast<string>().StartsWith("-") select s;

var applicable = from b in discounts where 
    b["YTM"].Cast<double>() > 3.0 select b;
MessageBox.Show(applicable.Count().ToString()); //<- returns 51
```

**Comment by mrworkman** [comment] 2017-09-02 17:00
I did a quick test, and I cannot reproduce the issue you're having. Can you attach a spreadsheet that demonstrates the problem?

**Comment by mrworkman** [comment] 2018-08-09 02:02
Since I wasn't able to reproduce this earlier, I'm going to close this issue. Please open a new issue if you're able to provide an excel spreadsheet that I can test with.

**Closed by mrworkman** 2018-08-09 02:02 UTC
Labels: Unconfirmed
